// <auto-generated />
using System;
using GloriousCore.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GloriousCore.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20190323164746_mig")]
    partial class mig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GloriousCore.Models.Data.Entities.CategoryDBO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("SectionId");

                    b.Property<string>("SectionName");

                    b.Property<string>("Slug");

                    b.Property<int>("Sorting");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("tblCategories");
                });

            modelBuilder.Entity("GloriousCore.Models.Data.Entities.GalleryDBO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Img");

                    b.Property<string>("ImgType");

                    b.Property<int>("ProductId");

                    b.HasKey("Id");

                    b.ToTable("tblGallery");
                });

            modelBuilder.Entity("GloriousCore.Models.Data.Entities.LoginDBO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Log");

                    b.Property<string>("Pass");

                    b.HasKey("Id");

                    b.ToTable("tblUser");
                });

            modelBuilder.Entity("GloriousCore.Models.Data.Entities.MaterialDBO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Slug");

                    b.Property<int>("Sorting");

                    b.HasKey("Id");

                    b.ToTable("tblMaterials");
                });

            modelBuilder.Entity("GloriousCore.Models.Data.Entities.OrderDBO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Addres");

                    b.Property<string>("City");

                    b.Property<bool>("Complete");

                    b.Property<string>("Mail");

                    b.Property<string>("Name");

                    b.Property<string>("Note");

                    b.Property<string>("Number");

                    b.Property<string>("Post");

                    b.HasKey("Id");

                    b.ToTable("tblOrders");
                });

            modelBuilder.Entity("GloriousCore.Models.Data.Entities.ProductDBO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryId");

                    b.Property<string>("CategoryName");

                    b.Property<string>("Description");

                    b.Property<decimal>("Discount");

                    b.Property<byte[]>("Img");

                    b.Property<string>("ImgType");

                    b.Property<int>("MaterialId");

                    b.Property<string>("MaterialName");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<string>("ProductCode");

                    b.Property<int>("SectionId");

                    b.Property<string>("SectionName");

                    b.Property<string>("Slug");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SectionId");

                    b.ToTable("tblProducts");
                });

            modelBuilder.Entity("GloriousCore.Models.Data.Entities.SectionDBO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Slug");

                    b.Property<int>("Sorting");

                    b.HasKey("Id");

                    b.ToTable("tblSections");
                });

            modelBuilder.Entity("GloriousCore.Models.Data.Entities.CategoryDBO", b =>
                {
                    b.HasOne("GloriousCore.Models.Data.Entities.SectionDBO", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GloriousCore.Models.Data.Entities.ProductDBO", b =>
                {
                    b.HasOne("GloriousCore.Models.Data.Entities.CategoryDBO", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GloriousCore.Models.Data.Entities.MaterialDBO", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GloriousCore.Models.Data.Entities.SectionDBO", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
